name: Deploy AWS Lambda Function

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: .

jobs:
  zip_lambda_code:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Zip Lambda Code"
        run: |
          zip demo.zip main.py

      - name: "Upload Lambda Code"
        uses: actions/upload-artifact@v3
        with:
          name: lambda_code
          path: |
            ./demo.zip

  deploy_lambda_function:
    runs-on: ubuntu-latest
    needs:
      - zip_lambda_code
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Initialise AWS CLI"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "<AWS_REGION>"
          aws-access-key-id: "<AWS_ACCESS_KEY_ID>"
          aws-secret-access-key: "<AWS_SECRET_ACCESS_KEY>"

      - name: "Download Lambda Code Zip"
        uses: actions/download-artifact@v3
        with:
          name: lambda_code
          path: .

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
          terraform_wrapper: true

      - name: "Terraform Init"
        run: terraform init -lock-timeout=15m

      - name: "Terraform Plan"
        run: terraform plan -out="plan.tfplan"
        env:
          TF_VAR_code_zip_path: demo.zip

      - name: "Terraform Apply"
        run: terraform apply -auto-approve plan.tfplan
